# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51960e4a56e0643a864580db43fbbc786cfb0871de4bdf738dcdffccc9bf728b1a574f628b6499288cfe8e62ee731ce6acfdce63cef5e8b17fc1f5dbb951a902

test:
  secret_key_base: 773ba55d02262aa5a81ca5760f2902f0cc0d22059b52f5020328866919d84d35b8ace07729c8f8df85d4700e70562f0e4ce2c4581cfea242185be8b685edc242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
